version: 1
formatters:
  brief:
    format: '%(levelname)s - %(message)s'
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: brief
loggers:
  gensim:
    level: WARNING
    handlers: [console]
  nonce2vec.main:
    level: INFO
    handlers: [console]
  nonce2vec.models.informativeness:
    level: DEBUG
    handlers: [console]
  nonce2vec.models.nonce2vec:
    level: DEBUG
    handlers: [console]
